### ISSUE TITLE
Onnx export of memory_fusion module

### ISSUE THREAD

**Issue by mgrewe** [heyoeyo/muggled_sam#3]
Hi @heyoeyo and muggled_sam community

thanks for the great work on the rather complex original source tree. It helps me a lot in studying the internals of SAMv2.

I came across the following issue when exporting the memory_fusion_model to onnx: 

> torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::polar' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

From what I understood and a quick grep, I suspect that might be due to usage to torch.polar here

https://github.com/heyoeyo/muggled_sam/blob/3ce2b48899e2ccec83422a006c0b80ad4f786c4a/lib/v2_sam/components/memfuse_attention.py#L281

and here 

https://github.com/heyoeyo/muggled_sam/blob/3ce2b48899e2ccec83422a006c0b80ad4f786c4a/lib/v2_sam/components/memfuse_attention.py#L287

Do you see any chance to fix this, may be by definition of a custom op?

Cheers
Martin

**Comment by heyoeyo** [comment]
Thanks for checking out the repo!

> You wrote that rotations via complex numbers is faster. Do you have any rough estimate? 

For the tiny model I get per-frame inference times of 26ms vs. 45ms(!). It's a bit surprising to me and might be very hardware specific. In case you want to try it, the numbers are from running the [video_segmentation](https://github.com/heyoeyo/muggled_sam/blob/main/simple_examples/video_segmentation.py) example with/without that `use_matrix_encoder` flag set.

> Or see a chance to export the RoPEAttention using RPEComplexEncoder?

There was some discussion of exporting with complex number support on the SAMv2 issue board (issue [#186](https://github.com/facebookresearch/segment-anything-2/issues/186)) and it seemed like there was some way to do it (with several fixes), though it might require rewriting some of the code slightly (getting rid of `.unsqueeze` apparently). Otherwise it may just be a matter of waiting for full complex number support from onnx.

**Comment by mgrewe** [comment]
Thanks for the quick answer and the insightful links. Very much appreciated!
