### ISSUE TITLE
Does memposenc index needs inversion?

### ISSUE THREAD

**Issue by mgrewe** [heyoeyo/muggled_sam#8]
Hi @heyoeyo 

I'm somewhat confused. When I understand the original [code](https://github.com/facebookresearch/sam2/blob/c2ec8e14a185632b0a5d8b161928ceb50197eddc/sam2/modeling/sam2_base.py#L582) right, then the most recent frame has t_pos = 1, such that 

```
maskmem_enc = (
                    maskmem_enc + self.maskmem_tpos_enc[self.num_maskmem - t_pos - 1]
                )
```
is using the second last additive offset (last being reserved for prompts). Do I understand it correct that most recent frame in

https://github.com/heyoeyo/muggled_sam/blob/764b10ccb59047dc25f33975e948fb0639056c09/lib/v2_sam/memory_fusion_model.py#L252

is using the first additive offset? I tried to reverse the order but it doesn't seem to have a huge effect.

**Comment by heyoeyo** [comment]
Hi @mgrewe 

The `_prepare_memory_conditioned_features` is probably the most confusing part of the whole SAM2 model, so it's definitely possible there's some (or many) discrepancies in the muggled sam implementation.

> When I understand the original code right, then the most recent frame has t_pos = 1

The code does something _very_ tricky here it seems... While the loop is over t_pos = 1 to 7, the result that get's stored uses a value of `out` which is derived from an [inverted copy](https://github.com/facebookresearch/sam2/blob/c2ec8e14a185632b0a5d8b161928ceb50197eddc/sam2/modeling/sam2_base.py#L540) of t_pos. The [simplified sequence](https://github.com/facebookresearch/sam2/blob/c2ec8e14a185632b0a5d8b161928ceb50197eddc/sam2/modeling/sam2_base.py#L540-L568) is something like:
```python
t_rel = self.num_maskmem - t_pos
prev_frame_idx = frame_idx - t_rel
out = output_dict["non_cond_frame_outputs"].get(prev_frame_idx, None)
t_pos_and_prevs.append((t_pos, out))
```

So even though the list stores `t_pos` in a [1,2,3,...] sequence, the corresponding outputs are in reversed order. That is, the `t_pos = 1` features are the oldest (since `t_rel = 7 - 1`, then `prev_frame_idx = frame_idx - 6`). At least that's my interpretation for now... every time I look at it I get confused lol.

Putting a print statement just after [that line](https://github.com/facebookresearch/sam2/blob/c2ec8e14a185632b0a5d8b161928ceb50197eddc/sam2/modeling/sam2_base.py#L582), like:
`print("  MASKIDX:", self.num_maskmem - t_pos - 1)`

Gives a sequence like:
```
Frame 1:
  MASKIDX: 6
Frame 2:
  MASKIDX: 6
  MASKIDX: 0
Frame 3:
  MASKIDX: 6
  MASKIDX: 1
  MASKIDX: 0
Frame 4:
  MASKIDX: 6
  MASKIDX: 2
  MASKIDX: 1
  MASKIDX: 0
etc.
```
So the first 6 is (presumably) the index from the prompt encoding, and then the sequence 6,0, then 6,1,0 then 6,2,1,0 etc. corresponds to including the single most recent, then 2 most recent then 3 most recent etc. frame encodings, which implies the most recent frame encoding uses index 0 of `maskmem_tpos_enc`.

Actually, the most recent commit of muggled sam fixed an [off-by-one error](https://github.com/heyoeyo/muggled_sam/blob/16d009cd9bd8f5de996fbdd251e847753f4bed37/lib/v2_sam/memory_fusion_model.py#L229) with this indexing (the most recent frame encoding was using index 1). Though as you say, even if the indexing is a bit off/reversed, it doesn't seem to make a big difference.
